# Generated by Django 4.1.6 on 2023-03-25 12:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("prestation", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ServicesGallery",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "image",
                    models.ImageField(max_length=255, upload_to="store/services"),
                ),
                (
                    "service",
                    models.ForeignKey(
                        default=None,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="prestation.services",
                    ),
                ),
            ],
            options={
                "verbose_name": "servicegallery",
                "verbose_name_plural": "service gallery",
            },
        ),
    ]
