# Generated by Django 4.1.6 on 2023-04-03 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("prestation", "0002_servicesgallery"),
    ]

    operations = [
        migrations.AddField(
            model_name="prestataires",
            name="en_ligne",
            field=models.BooleanField(default=False),
        ),
    ]
